#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $VOTE_DB_USER WITH PASSWORD '$VOTE_DB_PASSWORD';
    CREATE DATABASE $VOTE_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $VOTE_DB_NAME TO $VOTE_DB_USER;
    ALTER DATABASE $VOTE_DB_NAME SET TIMEZONE='Europe/Amsterdam';
    \c $VOTE_DB_NAME
    ALTER SCHEMA public OWNER TO $VOTE_DB_USER;
    GRANT ALL PRIVILEGES ON SCHEMA public TO $VOTE_DB_USER;
EOSQL